# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlockScribe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  pod 'KindeSDK'
  pod 'AWSAPIGateway'
  pod 'Stripe', '23.0.0'
  pod 'StripePaymentSheet', '23.0.0'

end
